**Ejercicio 1**: Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).

In [75]:
import numpy as np

matrix = np.arange(1,65,1)
matrix = matrix.reshape(8,8)
print(matrix)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


**Ejercicio 2**:

i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [114]:
import numpy as np

arr = np.arange(1,65,1)
matrix = arr.reshape(8,8).T
arr = np.char.mod('%d', arr)
mask = ['3' in number for number in arr]
mask = np.reshape(mask, (8,8)).T
modified_matrix = np.ma.masked_array(matrix, mask)
print(modified_matrix.filled(-99))


[[  1   9  17  25 -99  41  49  57]
 [  2  10  18  26 -99  42  50  58]
 [-99  11  19  27 -99 -99  51  59]
 [  4  12  20  28 -99  44  52  60]
 [  5 -99  21  29 -99  45 -99  61]
 [  6  14  22 -99 -99  46  54  62]
 [  7  15 -99 -99 -99  47  55 -99]
 [  8  16  24 -99  40  48  56  64]]
