**Ejercicio 1**: Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).

In [2]:
import numpy as np

matrix = np.arange(1,65,1)
matrix = matrix.reshape(8,8)
print(matrix)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


**Ejercicio 2**:

i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [3]:
import numpy as np

arr = np.arange(1,65,1)
matrix = arr.reshape(8,8).T
arr = np.char.mod('%d', arr)
mask = ['3' in number for number in arr]
mask = np.reshape(mask, (8,8)).T
modified_matrix = np.ma.masked_array(matrix, mask).filled(-99)
print(modified_matrix)


[[  1   9  17  25 -99  41  49  57]
 [  2  10  18  26 -99  42  50  58]
 [-99  11  19  27 -99 -99  51  59]
 [  4  12  20  28 -99  44  52  60]
 [  5 -99  21  29 -99  45 -99  61]
 [  6  14  22 -99 -99  46  54  62]
 [  7  15 -99 -99 -99  47  55 -99]
 [  8  16  24 -99  40  48  56  64]]


**Ejercicio 3:** 
i. Reproducir la matriz B:

[[0.4 0.41 0.42 0.43 0.44]

[0.45 0.46 0.47 0.48 0.49]

[0.5 0.51 0.52 0.53 0.54]

[0.55 0.56 0.57 0.58 0.59]

[0.6 0.61 0.62 0.63 0.64]

[0.65 0.66 0.67 0.68 0.69]

[0.7 0.71 0.72 0.73 0.74]

[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

v. Guardar en un archivo.

In [6]:
B = np.arange(0.40, 0.80, 0.01)
B = np.reshape(B, (8,5))

new_matrix = np.concatenate((modified_matrix, B), axis = 1)
column_means = np.mean(new_matrix, axis = 0)
final_matrix = np.concatenate((new_matrix, column_means.reshape(1,13)), axis = 0)
row_max = np.max(final_matrix, axis = 1)
final_matrix = np.concatenate((final_matrix, row_max.reshape(9,1)), axis = 1)
cols, rows = final_matrix.shape[0], final_matrix.shape[1]
final_matrix[cols-1][rows-1] = 0

np.savetxt('datos.csv', final_matrix, delimiter=',', fmt='%.2f', header="1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, max")